name: god

on: pull_request

jobs:
  checkstyle_job:
    runs-on: ubuntu-latest
    name: checkstyle_id_1
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run check style
      uses: nikitasavinov/checkstyle-action@master
      with:
        level: error
        reporter: 'github-pr-review'
        github_token: ${{ secrets.GITHUB_TOKEN }}