on: pull_request

jobs:
  checkstyle_job:
    runs-on: ubuntu-latest
    name: checkstyle_id_1
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run check style
      uses: nikitasavinov/checkstyle-action@master
      with:
        reporter: 'github-pr-review'
        tool_name: 'checkstyle_id_2'
        filter_mode: nofilter
        github_token: ${{ secrets.GITHUB_TOKEN }}
