- name: Run java checkstyle
  # You may pin to the exact commit or the version.
  # uses: nikitasavinov/checkstyle-action@d236d4d9a3563684368581f1127f7e4773013e9d
  uses: nikitasavinov/checkstyle-action@0.3.1
  with:
    # GITHUB_TOKEN.
    github_token: # optional, default is ${{ github.token }}
    # Report level for reviewdog [info,warning,error]
    level: # optional, default is info
    # Reporter of reviewdog command [github-pr-check,github-pr-review]
    reporter: # optional, default is github-pr-check
    # Filtering for the reviewdog command [added,diff_context,file,nofilter].
Default is `added`.

    filter_mode: # optional, default is added
    # Exit code for reviewdog when errors are found [true,false]
Default is `false`.

    fail_on_error: # optional, default is false
    # Checkstyle config file
    checkstyle_config: # default is google_checks.xml
    # Working directory relative to the root directory.
    workdir: # optional, default is .
    # Tool name to use for reviewdog reporter
    tool_name: # optional, default is reviewdog
